#!/bin/bash

# A quick and dirty recryptor tool
# It does not handle user interaction except via the agent

OPTS=("--batch" "--status-fd" "2")
D_COMMAND=("-d" "-")
D_OPTS=()
E_OPTS=()

# Attempt to distribute command-line options to the appropriate process(es)
while [[ -n $1 ]]; do
    case $1 in
        --ignore-mdc-error|--ignore-crc-error|--allow-multiple-messages|--ignore-time-conflict|--ignore-valid-from)
            # Decryption options that take no arguments
            D_OPTS+=("$1")
            ;;
        --decrypt|-d)
            # Override the decryption command (e.g. to read from a file)
            D_COMMAND=("$1" "$2")
            shift
            ;;
        --sign|-s|--armor|-a|--throw-key-ids|--for-your-eyes-only|--default-recipient-self)
            # Encryption options that take no arguments
            E_OPTS+=("$1")
            ;;
        --recipient|-r|--hidden-recipient|-R|--output|-o|--set-filename|--default-key)
            # Encryption options that take arguments
            E_OPTS+=("$1" "$2")
            shift
            ;;
        --debug-all|--no-default-keyring)
            # General options that take no arguments
            OPTS+=("$1")
            ;;
        --debug-level|--debug|--keyring|--secret-keyring|--homedir|--options)
            # General options that take arguments
            OPTS+=("$1" "$2")
            shift
            ;;
        *)
            echo "Ignoring: $1" >>/dev/fd/2
            ;;
    esac
    shift
done

gpg "${OPTS[@]}" "${D_OPTS[@]}" -o - "${D_COMMAND[@]}" | gpg "${OPTS[@]}" "${E_OPTS[@]}" -e -
